### ISSUE TITLE
Console: cannot access user console

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#312]
it refers to a resource that is not accessible:
![image](https://user-images.githubusercontent.com/100349014/220312884-17e6c9a5-5f06-45a8-aae0-688759d27c9d.png)

UI message:
![image](https://user-images.githubusercontent.com/100349014/220313463-69fd631b-efd0-4512-9d76-ab098b1cb51e.png)

**Comment by matteo-s** [comment]
The user console is in a subproject under `/user-console`.
In order to use it you need to build both the console and the main java project with maven (`mvn package`)
This will build and copy the user console inside the resources.
If you build manually (for example with Eclipse) you'll need to synchronize your project with maven or manually build and copy the console.
