### ISSUE TITLE
UI: cannot add multiple admin role (on multiple realms) to an invited user (subject id)

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#323]
If you invite the same user to multiple realms, when the user logs in, only the first realm on which admin/developer was placed appears. 
It can switch to the other realm by changing the url. 
But the problem is that if you want to add the ADMIN role for the second realm (with the invitation only the DEVELOPER is activated by default), you can't because the toggle is already active on another realm.

**Comment by matteo-s** [comment]
Switching the realm in the dev console happens via a dropdown selector on the side menu: click on the realm name and select a new realm to switch the context.

Updating the authorities works: it is possible to enable/disable roles and the context is correct. Only the visualization is broken, due to a missing filter.
