### ISSUE TITLE
Support for a configurable default provider in the system realm

### ISSUE THREAD

**Issue by thomaschiozzi-tndigit** [scc-digitalhub/AAC#529]
Currently, the default provider(s) for the realm system (internal+password) has hard-coded configurations and cannot be changed, in particular they are defined in this block of code where the necessity of a configurable provider is also hinted.

https://github.com/scc-digitalhub/AAC/blob/8bf546ebcc4568475026b0a10e6aa06480dc0592/src/main/java/it/smartcommunitylab/aac/identity/service/IdentityProviderService.java#L58-L67
and
https://github.com/scc-digitalhub/AAC/blob/8bf546ebcc4568475026b0a10e6aa06480dc0592/src/main/java/it/smartcommunitylab/aac/identity/service/IdentityProviderService.java#L71-L77

Support for a configurable default provider for realm system is desirable if, for exmaple, the provider must respect some company policy,  such as disabling new user registrations for that provider in the realm system.

**Comment by matteo-s** [comment]
This has a major impact on system configuration, for example with multiple nodes. System configuration has to be immutable, because it isn't versioned.
```
internalConfig.setVersion(1); 
```

The `TODO make configurable` comment hinted at letting users choose whether to enable or not the internal and password providers, not on letting them change the config.

In order to make this modifiable we should at minimum handle versioning.

**Comment by thomaschiozzi-tndigit** [comment]
> The `TODO make configurable` comment hinted at letting users choose whether to enable or not the internal and password providers, not on letting them change the config.

Thanks for the clarification.

If I understand correctly, disabling a the default provider (assuming that it is possible) for realm system and creating a new one defined in the `application.yml` is enough to reach the desired result, which was

>>[only one] provider [that] must respect some company policy, such as disabling new user registrations for that provider in the realm system.

Am I correct or am I missing something?

**Comment by matteo-s** [comment]
Yes, that may achieve the desired result, but might make the admin account unavailable, because it is (currently) bound to the hardcoded idp. Although, given that the link is (supposedly) via idp name, you could probably disable the hardcoded idps, make the equivalent ones (=same ids+names) in application.yaml and get a working config.

It might still break during bootstrap due to the different ordering of operations.

**Comment by thomaschiozzi-tndigit** [comment]
Closing as the provided answers were sufficiently exhaustive and provided enough information on how to currently handle the usage of the default provider.
