### ISSUE TITLE
create account as internal user is not working with the default idp config

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#65]
**how to replicate error:**

- run the project aac
- enter in administration mode
- create a realm
- enter in user mode
- choose realm
- choose "Non sei registrato? Iscriviti!"
- compile form and go "Registrati" button

the system say "Utente o password non validi" (see image) and account is not created
in the log is not generated any message

![image](https://user-images.githubusercontent.com/100349014/155736391-6f1ff1c6-b9b9-4adc-abd4-9bd23874b444.png)

**Comment by matteo-s** [comment]
what is the provider policy for password?
The password in screenshot is 15 chars, so check if the provider has a maxLength of 15+

**Comment by gianpaolo-tndigit** [comment]
the first time the maxLenght was not set, then i put minLength 4 and maxLength 20, then I try again but not worked.
The idp is an internal idp activated

**Comment by matteo-s** [comment]
can't reproduce.
Please export the provider configuration (via action button from dev console) and paste the yaml so I can test the same config.

**Comment by gianpaolo-tndigit** [comment]
I'm sorry the parameter maxLength was not set, cause you have to DISABLE the IDP before you do changes. If you don't DISABLE it, you can "EDIT" but when you edit, the system does not save changes.

**Comment by matteo-s** [comment]
The SAVE button should be disabled for active providers, so you shouldn't be able to save the edit until you disable the idp.
The UI should be more clear, let's open a new issue.

Instead, I'm gonna reopen this because from your explanation I discovered that newly created internal idps don't have a working configuration "out-of-the-box": minLength and maxLength are not set and thus the default config will apply, but there is no indication which instructs admins and users on the default policy.

**Comment by matteo-s** [comment]
to recap:
- create a new internal provider
- activate with default config
- try to register a user

The default password policy will apply without any indication of this.
Furthermore, the UI presents a screen with *blank settings* for minLength/maxLength, which suggests no criteria are applied. This is wrong, because in this case the default policy from application.properties will be selected.
